# Generated by Django 5.1.6 on 2025-03-10 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.CharField(default='null', max_length=50),
        ),
    ]
