# Generated by Django 5.1.6 on 2025-03-06 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0004_alter_comment_commission'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_on'], 'verbose_name': 'comment', 'verbose_name_plural': 'comments'},
        ),
        migrations.AlterModelOptions(
            name='commission',
            options={'ordering': ['created_on'], 'verbose_name': 'commission', 'verbose_name_plural': 'commissions'},
        ),
    ]
